description: "Install MySQL Server"

variables:
    use_legacy_templating: true
    mysql_bind_address: 0.0.0.0
    mysql_server_id: ~
    mysql_server_package: mysql-server
    mysql_root_password: ~
    mysql_replication_user: repln
    mysql_replication_password: ~

tasks:
    -
      name: "Copy a file of debconf database entries to answer the MySQL/MariaDB root password question"
      command: "fs:copy"
      arguments:
          src: "!{{ mod_path}}/assets/debconf-selections.template"
          dest: "/tmp/debconf-selections-{{ mysql_server_package }}"
    -
      name: "Insert the debconf database MySQL root password entries"
      command: "debconfdb:set"
      sudo: true
      arguments:
          file: "/tmp/debconf-selections-{{ mysql_server_package }}"
    -
      name: "Install package {{ mysql_server_package }} and php5-mysql"
      command: "apt-get:install"
      sudo: true
      max_runtime: 600
      arguments:
          package: "{{ mysql_server_package }} php5-mysql"
    -
      name: "Copy tuning configuration to the server"
      command: "fs:copy"
      sudo: true
      arguments:
          src: "!{{ mod_path}}/assets/tuning.cnf.template"
          dest: "/etc/mysql/conf.d/tuning.cnf"
      trigger: "Restart mysql-server"
    -
      name: "Copy replication master configuration to the master"
      command: "fs:copy"
      sudo: true
      arguments:
          src: "!{{ mod_path}}/assets/master.cnf.template"
          dest: "/etc/mysql/conf.d/master.cnf"
      host_filter: "host.variables['replication_role'] == 'master'"
      trigger: "Restart mysql-server"
    -
      name: "Copy replication slave configuration to the slave"
      command: "fs:copy"
      sudo: true
      arguments:
          src: "!{{ mod_path}}/assets/slave.cnf.template"
          dest: "/etc/mysql/conf.d/slave.cnf"
      host_filter: "host.variables['replication_role'] == 'slave'"
      trigger: "Restart mysql-server"
    -
      name: "Create a MySQL remote root account for management"
      command: "mysql:adduser"
      arguments:
          url: "mysql://root:{{{ mysql_root_password }}}@localhost/"
          username: "root"
          password: "{{{ mysql_root_password }}}"
          allowed-host: "any"
          grant: "all"
          grant-level: "*.*"
          can-grant: ~
    -
      name: "Create a MySQL user account for replication"
      command: "mysql:adduser"
      arguments:
          url: "mysql://root:{{{ mysql_root_password }}}@localhost/"
          username: "{{{ mysql_replication_user }}}"
          password: "{{{ mysql_replication_password }}}"
          allowed-host: "%"
          grant: "REPLICATION SLAVE"
          grant-level: "*.*"
      host_filter: "host.variables['replication_role']"


triggers:
    -
      name: "Restart mysql-server"
      command: "service:restart"
      sudo: true
      arguments:
          name: "mysql"
